{
  "kind": "SealedSecret",
  "apiVersion": "bitnami.com/v1alpha1",
  "metadata": {
    "name": "github-registry-secret",
    "namespace": "default",
    "creationTimestamp": null
  },
  "spec": {
    "template": {
      "metadata": {
        "name": "github-registry-secret",
        "namespace": "default",
        "creationTimestamp": null
      },
      "type": "kubernetes.io/dockerconfigjson"
    },
    "encryptedData": {
      ".dockerconfigjson": "AgADuW5F8GkVVyubmu/ZxIMGSZ5FpxFWZa7oME2zwvLMbIHrrsLMW8NZmk6J3k1P3EgS8GKBnL1ASI7C4aUCZuyDFeRqP2dieadbzP1DVQJS6Prf1jEl2qYPmvNhGnDqFtDRg7Q6EKeL4Ro1oOB0BmkMQoyF6vOEZs/EJ6Hv0HoyWDhCfJB6WHbqGlxMLZ2VGhC94jMxe0DpVac5WF7VPV4L6IBK+UJwRpzBwAX8LEOC9EBUoL8AVBYVCJkNRzcGOgA2Aldbg/puf/gg0/Gphw5+mGG74F0OqplWSmOwFnkzJjmc+exx9ra0F1pZ2Tg1r/fHRLEW6x6JPg/88tV5HasNNu4SOgZncPcuFrI2nEMwtzdZBmd3ankqNuG3spGiaikKm2NL3diDyHAwMCT0n1bzR6GIs1l2mRQCYdtlRyqPR+B424ayHHBSDyqUlDjLSneeODs73Lg+CbvRW4Tdwkj05idQtBuXes8E4A3Fq6kSbugh8otmcAaGunzgoUzULbjUb8qjHyO69gpBlDidAjPC9ekTnrh72YVOda8gpJ1dfgpb3iLNqgXRo84jIK00h8c2VHiHkFcbolRocGL6iOIWFdGdRBjD9LtPpf3s97JJxd1iyGiCUbYDz6nzPaIXDV1yxjBKjPBNAOiNMvlNj0XH0wGra6ik6+0LpMidKY//CJRTa3m+dyhkMhKFaK5dY0uj4JzSQUNUmmJaSf6jSYSk7ioUVWkp3cDxK0nxoVxCLY0R+LRsUy/Mlv7+BMx/23L+8ri1gHbRJwegOPS7Jm5UVwoXEqA38FFm1VA1v6AV4r25WWPH6hFFIu7ibY3HBMDU"
    }
  }
}
