# deploy/minio-controller/controller.yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: minio
  namespace: argocd
spec:
  project: default
  source:
    chart: minio
    repoURL: registry-1.docker.io/bitnamicharts
    targetRevision: 14.7.1
    helm:
      releaseName: minio
      parameters:
        - name: auth.rootUser
          value: minio-admin
        - name: auth.rootPassword
          value: minio-secret-password
  destination:
    server: "https://kubernetes.default.svc"
    namespace: default
