apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      imagePullSecrets:
        - name: github-registry-secret
      containers:
        - name: api
          image: ghcr.io/lx-team-content/interactive-video-api:latest
          ports:
            - containerPort: 3000
          volumeMounts:
            - name: data-volume
              mountPath: /app/data
            - name: config-volume
              mountPath: /app/assets/config.json
              subPath: config.json
      volumes:
        - name: data-volume
          hostPath:
            path: /path/on/host/data
        - name: config-volume
          configMap:
            name: app-config
